// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
	v1beta1 "k8s.io/api/events/v1beta1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	events "k8s.io/kubernetes/pkg/apis/events"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1beta1_Event_To_events_Event,
		Convert_events_Event_To_v1beta1_Event,
		Convert_v1beta1_EventAction_To_events_EventAction,
		Convert_events_EventAction_To_v1beta1_EventAction,
		Convert_v1beta1_EventSeries_To_events_EventSeries,
		Convert_events_EventSeries_To_v1beta1_EventSeries,
		Convert_v1beta1_EventSource_To_events_EventSource,
		Convert_events_EventSource_To_v1beta1_EventSource,
	)
}

func autoConvert_v1beta1_Event_To_events_Event(in *v1beta1.Event, out *events.Event, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.EventTime = in.EventTime
	out.Series = (*events.EventSeries)(unsafe.Pointer(in.Series))
	if err := Convert_v1beta1_EventSource_To_events_EventSource(&in.Origin, &out.Origin, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_EventAction_To_events_EventAction(&in.Action, &out.Action, s); err != nil {
		return err
	}
	out.Object = (*v1.ObjectReference)(unsafe.Pointer(in.Object))
	out.SecondaryObject = (*v1.ObjectReference)(unsafe.Pointer(in.SecondaryObject))
	out.Severity = events.EventSeverity(in.Severity)
	out.Message = in.Message
	return nil
}

// Convert_v1beta1_Event_To_events_Event is an autogenerated conversion function.
func Convert_v1beta1_Event_To_events_Event(in *v1beta1.Event, out *events.Event, s conversion.Scope) error {
	return autoConvert_v1beta1_Event_To_events_Event(in, out, s)
}

func autoConvert_events_Event_To_v1beta1_Event(in *events.Event, out *v1beta1.Event, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.EventTime = in.EventTime
	out.Series = (*v1beta1.EventSeries)(unsafe.Pointer(in.Series))
	if err := Convert_events_EventSource_To_v1beta1_EventSource(&in.Origin, &out.Origin, s); err != nil {
		return err
	}
	if err := Convert_events_EventAction_To_v1beta1_EventAction(&in.Action, &out.Action, s); err != nil {
		return err
	}
	out.Object = (*v1.ObjectReference)(unsafe.Pointer(in.Object))
	out.SecondaryObject = (*v1.ObjectReference)(unsafe.Pointer(in.SecondaryObject))
	out.Severity = v1beta1.EventSeverity(in.Severity)
	out.Message = in.Message
	return nil
}

// Convert_events_Event_To_v1beta1_Event is an autogenerated conversion function.
func Convert_events_Event_To_v1beta1_Event(in *events.Event, out *v1beta1.Event, s conversion.Scope) error {
	return autoConvert_events_Event_To_v1beta1_Event(in, out, s)
}

func autoConvert_v1beta1_EventAction_To_events_EventAction(in *v1beta1.EventAction, out *events.EventAction, s conversion.Scope) error {
	out.Action = in.Action
	out.Reason = in.Reason
	return nil
}

// Convert_v1beta1_EventAction_To_events_EventAction is an autogenerated conversion function.
func Convert_v1beta1_EventAction_To_events_EventAction(in *v1beta1.EventAction, out *events.EventAction, s conversion.Scope) error {
	return autoConvert_v1beta1_EventAction_To_events_EventAction(in, out, s)
}

func autoConvert_events_EventAction_To_v1beta1_EventAction(in *events.EventAction, out *v1beta1.EventAction, s conversion.Scope) error {
	out.Action = in.Action
	out.Reason = in.Reason
	return nil
}

// Convert_events_EventAction_To_v1beta1_EventAction is an autogenerated conversion function.
func Convert_events_EventAction_To_v1beta1_EventAction(in *events.EventAction, out *v1beta1.EventAction, s conversion.Scope) error {
	return autoConvert_events_EventAction_To_v1beta1_EventAction(in, out, s)
}

func autoConvert_v1beta1_EventSeries_To_events_EventSeries(in *v1beta1.EventSeries, out *events.EventSeries, s conversion.Scope) error {
	out.UID = in.UID
	out.Count = in.Count
	out.LastObservedTime = in.LastObservedTime
	out.LastHeartbeat = in.LastHeartbeat
	out.FinishMarker = in.FinishMarker
	return nil
}

// Convert_v1beta1_EventSeries_To_events_EventSeries is an autogenerated conversion function.
func Convert_v1beta1_EventSeries_To_events_EventSeries(in *v1beta1.EventSeries, out *events.EventSeries, s conversion.Scope) error {
	return autoConvert_v1beta1_EventSeries_To_events_EventSeries(in, out, s)
}

func autoConvert_events_EventSeries_To_v1beta1_EventSeries(in *events.EventSeries, out *v1beta1.EventSeries, s conversion.Scope) error {
	out.UID = in.UID
	out.Count = in.Count
	out.LastObservedTime = in.LastObservedTime
	out.LastHeartbeat = in.LastHeartbeat
	out.FinishMarker = in.FinishMarker
	return nil
}

// Convert_events_EventSeries_To_v1beta1_EventSeries is an autogenerated conversion function.
func Convert_events_EventSeries_To_v1beta1_EventSeries(in *events.EventSeries, out *v1beta1.EventSeries, s conversion.Scope) error {
	return autoConvert_events_EventSeries_To_v1beta1_EventSeries(in, out, s)
}

func autoConvert_v1beta1_EventSource_To_events_EventSource(in *v1beta1.EventSource, out *events.EventSource, s conversion.Scope) error {
	out.Component = in.Component
	out.ID = in.ID
	return nil
}

// Convert_v1beta1_EventSource_To_events_EventSource is an autogenerated conversion function.
func Convert_v1beta1_EventSource_To_events_EventSource(in *v1beta1.EventSource, out *events.EventSource, s conversion.Scope) error {
	return autoConvert_v1beta1_EventSource_To_events_EventSource(in, out, s)
}

func autoConvert_events_EventSource_To_v1beta1_EventSource(in *events.EventSource, out *v1beta1.EventSource, s conversion.Scope) error {
	out.Component = in.Component
	out.ID = in.ID
	return nil
}

// Convert_events_EventSource_To_v1beta1_EventSource is an autogenerated conversion function.
func Convert_events_EventSource_To_v1beta1_EventSource(in *events.EventSource, out *v1beta1.EventSource, s conversion.Scope) error {
	return autoConvert_events_EventSource_To_v1beta1_EventSource(in, out, s)
}
