// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package events

import (
	core_v1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	reflect "reflect"
)

func init() {
	SchemeBuilder.Register(RegisterDeepCopies)
}

// RegisterDeepCopies adds deep-copy functions to the given scheme. Public
// to allow building arbitrary schemes.
func RegisterDeepCopies(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedDeepCopyFuncs(
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_events_Event, InType: reflect.TypeOf(&Event{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_events_EventAction, InType: reflect.TypeOf(&EventAction{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_events_EventSeries, InType: reflect.TypeOf(&EventSeries{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_events_EventSource, InType: reflect.TypeOf(&EventSource{})},
	)
}

// DeepCopy_events_Event is an autogenerated deepcopy function.
func DeepCopy_events_Event(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*Event)
		out := out.(*Event)
		*out = *in
		if newVal, err := c.DeepCopy(&in.ObjectMeta); err != nil {
			return err
		} else {
			out.ObjectMeta = *newVal.(*v1.ObjectMeta)
		}
		out.EventTime = in.EventTime.DeepCopy()
		if in.Series != nil {
			in, out := &in.Series, &out.Series
			*out = new(EventSeries)
			if err := DeepCopy_events_EventSeries(*in, *out, c); err != nil {
				return err
			}
		}
		if in.Object != nil {
			in, out := &in.Object, &out.Object
			*out = new(core_v1.ObjectReference)
			**out = **in
		}
		if in.SecondaryObject != nil {
			in, out := &in.SecondaryObject, &out.SecondaryObject
			*out = new(core_v1.ObjectReference)
			**out = **in
		}
		return nil
	}
}

// DeepCopy_events_EventAction is an autogenerated deepcopy function.
func DeepCopy_events_EventAction(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*EventAction)
		out := out.(*EventAction)
		*out = *in
		return nil
	}
}

// DeepCopy_events_EventSeries is an autogenerated deepcopy function.
func DeepCopy_events_EventSeries(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*EventSeries)
		out := out.(*EventSeries)
		*out = *in
		out.LastObservedTime = in.LastObservedTime.DeepCopy()
		out.LastHeartbeat = in.LastHeartbeat.DeepCopy()
		return nil
	}
}

// DeepCopy_events_EventSource is an autogenerated deepcopy function.
func DeepCopy_events_EventSource(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*EventSource)
		out := out.(*EventSource)
		*out = *in
		return nil
	}
}
